create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  description text not null,
  lat double precision,
  lng double precision,
  location_label text,
  severity text default 'Medium',
  status text default 'Pending',
  photo_url text,
  assigned_to uuid,
  assigned_org_name text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.reports enable row level security;

create policy if not exists "Users can view their own reports" on public.reports
  for select using (auth.uid() = user_id or coalesce((auth.jwt() -> 'user_metadata' ->> 'role'), '') = 'org');

create policy if not exists "Users can insert their own reports" on public.reports
  for insert with check (auth.uid() = user_id);

create policy if not exists "Users can update their own reports" on public.reports
  for update using (auth.uid() = user_id or coalesce((auth.jwt() -> 'user_metadata' ->> 'role'), '') = 'org');
